# Site Info
title:              "Blog"
description:        "A blog of all sorts."

# Google APIs
google_verify:      false # Your Google Verification - set to 'false' to disable
google_analytics:   false # Your Google Analytics code - set to 'false' to disable

# Author Info
author_name:        "ysoh286"
author_email:       ysoh286@gmail.com
author_gravatar:    false # Gravatar md5 hash (of email) here for logo - set to 'false' to disable
twitter_username:   false # set to 'false' to disable
github_username:    ysoh286 # set to 'false' to disable

# Site Settings
url:                https://ysoh286.github.io/blog # main url
baseurl:            "" # for gh-pages
permalink:          /:title # Post permalink
timezone:           Pacific/Auckland # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
