name: cicd
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - name: Upload build artifacts for deployment
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      # deploy build folder to gh-pages
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
