name: cicd
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Lint checks
        run: npm run lint

      - name: Build artifacts
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build

      - name: Upload build artifacts for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    # if: github.ref == 'refs/heads/master'
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
